### ISSUE TITLE
Site must allow iframing

### ISSUE THREAD

**Issue by MethodGrab** [MethodGrab/firefox-custom-new-tab-page#12]
The technique this extension uses to keep focus in the address bar means the site you choose as your new tab page must allow iframing.

Sites that set the `X-Frame-Options: DENY` or `X-Frame-Options: SAMEORIGIN` [header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) will not load inside the new tab page. Instead you will see a `Blocked by X-Frame-Options Policy` error:

![image](https://user-images.githubusercontent.com/2421069/82698719-34d08e80-9c63-11ea-8772-82a70996eb61.png)

**Comment by niyumard** [comment]
Is it possible that the addon opens link in a new tab and closes the current tab? That'd be a nice workaround.

**Comment by MethodGrab** [comment]
> Is it possible that the addon opens link in a new tab and closes the current tab? That'd be a nice workaround.
> Also going to URLs using javascript and changing window.location works. This could be another workaround.

@niyumard I think you're talking about #1.  
This issue is about some sites being unable to be used as the new tab URL, which #19 should fix.

**Comment by MethodGrab** [comment]
Published on AMO as v1.0.0.
