### ISSUE TITLE
Writing a URL before the tab finishes loading clears my writing

### ISSUE THREAD

**Issue by Petemir** [MethodGrab/firefox-custom-new-tab-page#17]
Hello, very nice extension, thank you for your work.

I'll admit this may be a bit of a corner case, but sometimes I open a new tab (ctrl+T) and start writing really fast, but the first letters of what I have written get erased when the extension focuses on the URL tab... I don't know if there's a way to solve this, nor if anyone else has noticed this problem.

Thanks!

**Comment by MethodGrab** [comment]
> Hello, very nice extension, thank you for your work.

You're welcome!

> ...when the extension focuses on the URL tab...

The extension itself doesn't actually do the focusing on the address bar. It uses the [`chrome_url_overrides.newtab`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_url_overrides) API to specify a custom file that is shown.

The behaviour of keeping the focus on the address bar is all handled by Firefox so I don't think there's anything that can be done by the extension to fix your issue.
