### ISSUE TITLE
Issue when opening links from other pages

### ISSUE THREAD

**Issue by siddhartpai** [MethodGrab/firefox-custom-new-tab-page#5]
When I middle-click on a link from an already open tab, it opens up a new tab and doesn't load anything. The new URL just sits in the address bar and doesn't load anything. Even if I press enter on the URL or try to reload the tab, it doesn't do anything.

This has started happening after I installed the extension. I'll also attach a screenshot the next time I face this issue.

**Comment by siddhartpai** [comment]
This only happens when opening new tabs and typing in the url and trying to load the page. This does not happen where some page already has been opened and I'm able to navigate from it to another page successfully

At this point of time, the web debugging console doesn't open.  But the firefox browser console can be opened. I see a couple of errors there. I'm attaching the errors below. 


`Error: WebExtension context not found! ExtensionParent.jsm:1229:13
uncaught exception: Object`


Is this relevant ?

**Comment by MethodGrab** [comment]
Thanks for taking the time to report this.
I am unable to reproduce this myself at the moment. Please could you provide the following information to help me investigate this further:
- Operating system name and version (e.g. Windows 7 Pro x64 SP1)
- Firefox release line (stable/nightly/developer edition) and version (e.g. Firefox stable v71.0 x64)
- The version of _Custom New Tab Page_ installed (e.g. v0.4.0)
- A step by step way to consistently reproduce this issue

**Comment by siddhartpai** [comment]
Thanks @MethodGrab for making the time to check this out. 

OS : Ubuntu 18.04, Linux, 4.15.0-70-generic #79-Ubuntu SMP x86_64 GNU/Linux
Browser : Firefox 71.0 (64 bit)
CustomNewTabPage : 0.4.0

Steps to reproduce :
This happens intermittently, not always.
1. Open a page with links. 
2. Middle click on a link .
    2.1 Go to the newly opened tab.
3. New page opens on a new tab, but doesn't load [Blank screen]

**Comment by siddhartpai** [comment]
Closing this issue, as this is still happening even after I've disabled the extension.
